# Generated by Django 6.0.4 on 2026-05-01 12:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='اسم التصنيف')),
                ('slug', models.SlugField(blank=True, unique=True)),
            ],
            options={
                'verbose_name': 'تصنيف',
                'verbose_name_plural': 'التصنيفات',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50, verbose_name='الاسم الأول')),
                ('last_name', models.CharField(max_length=50, verbose_name='الاسم الأخير')),
                ('phone_number', models.CharField(max_length=20, verbose_name='رقم الهاتف')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='البريد الإلكتروني')),
                ('city', models.CharField(max_length=100, verbose_name='المدينة / المحافظة')),
                ('address', models.TextField(verbose_name='العنوان بالتفصيل')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الطلب')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('status', models.CharField(choices=[('Pending', 'قيد الانتظار'), ('Processing', 'جاري التجهيز'), ('Shipped', 'تم الإرسال لشركة الشحن'), ('Delivered', 'تم التوصيل'), ('Cancelled', 'ملغي')], default='Pending', max_length=20, verbose_name='حالة الطلب')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='ملاحظات إضافية من العميل')),
            ],
            options={
                'verbose_name': 'طلب',
                'verbose_name_plural': 'الطلبات',
                'ordering': ('-created',),
            },
        ),
        migrations.CreateModel(
            name='Carpet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='اسم السجادة')),
                ('description', models.TextField(verbose_name='الوصف')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='السعر')),
                ('image', models.ImageField(upload_to='carpets/%Y/%m/%d', verbose_name='صورة السجادة')),
                ('length', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='الطول (بالمتر)')),
                ('width', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='العرض (بالمتر)')),
                ('material', models.CharField(blank=True, max_length=100, verbose_name='الخامة')),
                ('available', models.BooleanField(default=True, verbose_name='متاح في المخزن')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='carpets', to='app1.category', verbose_name='التصنيف')),
            ],
            options={
                'verbose_name': 'سجادة',
                'verbose_name_plural': 'السجاد',
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='السعر وقت الشراء')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='الكمية')),
                ('carpet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_items', to='app1.carpet', verbose_name='السجادة')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='app1.order', verbose_name='الطلب')),
            ],
            options={
                'verbose_name': 'عنصر الطلب',
                'verbose_name_plural': 'عناصر الطلب',
            },
        ),
    ]
