# Generated by Django 6.0.4 on 2026-05-01 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carpet',
            name='image',
        ),
        migrations.AddField(
            model_name='carpet',
            name='image_url',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='رابط صورة السجادة'),
        ),
    ]
