# Generated by Django 6.0.4 on 2026-05-01 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_remove_carpet_image_carpet_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='carpet',
            name='stock',
            field=models.PositiveIntegerField(default=10, verbose_name='الكمية المتاحة'),
        ),
    ]
