# Generated by Django 6.0.4 on 2026-05-02 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_carpet_stock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Pending', 'قيد الانتظار'), ('Processing', 'جاري التجهيز'), ('Shipped', 'تم الإرسال لشركة الشحن'), ('Delivered', 'تم التوصيل'), ('Cancelled', 'ملغي (من قبل العميل)'), ('Returned', 'مرتجع (لم يتم الاستلام)')], default='Pending', max_length=20, verbose_name='حالة الطلب'),
        ),
    ]
